"""add reply and reply_at to post_comments

Revision ID: ac10bfb954ef
Revises: 012
Create Date: 2026-07-17 15:16:19.206611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac10bfb954ef'
down_revision: Union[str, None] = '012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('reply', sa.Text(), nullable=True))
    op.add_column('post_comments', sa.Column('reply_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_comments', 'reply_at')
    op.drop_column('post_comments', 'reply')
    # ### end Alembic commands ###
