"""add item_type to tool_files

Revision ID: 0f648c83734e
Revises: b014bookreply01
Create Date: 2026-07-18 12:16:58.308363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f648c83734e'
down_revision: Union[str, None] = 'b014bookreply01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_files', sa.Column('item_type', sa.String(length=10), server_default='file', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_files', 'item_type')
    # ### end Alembic commands ###
