"""add roadmap_resources table

Revision ID: 924fd7436732
Revises: b7c1d4e9a205
Create Date: 2026-07-31 15:39:52.756012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924fd7436732'
down_revision: Union[str, None] = 'b7c1d4e9a205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_slug', sa.String(length=20), nullable=False),
    sa.Column('competency_slug', sa.String(length=50), nullable=True),
    sa.Column('area_slug', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('reading_time', sa.String(length=30), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('has_persian', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('homework_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_resources_level_slug'), 'roadmap_resources', ['level_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_resources_level_slug'), table_name='roadmap_resources')
    op.drop_table('roadmap_resources')
    # ### end Alembic commands ###
